folio-org/edge-patron

pom.xml, src/main/java/org/folio/edge/patron/PatronHandler.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java
Utilize the new API key format in edge-common-0.2.1-SNAPSHOT...
Incorporates a salt/clientId and an institutional userId, to make it harder to guess an API key.
e.g.
```
clientID/salt = gYn0uFv3Lf (random string)
tenantID = fs00000000
username = fs00000000 (same as tenantID)
delim = "_"
apiKey = urlBase64(gYn0uFv3Lf_fs00000000_fs00000000) 
apiKey = Z1luMHVGdjNMZl9mczAwMDAwMDAwX2ZzMDAwMDAwMD=A
```
The benefit of doing this is that the clientId would only be known to us, so even if someone knew the tenantId, and was able to find or guess the institutional user's username, they would still have to guess or brute force the clientID.
=> Improved API Keys

pom.xml, ramls/charge.json, ramls/patron.xsd, src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/model/Charge.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/model/AccountTest.java, src/test/java/org/folio/edge/patron/model/ChargeTest.java, src/test/java/org/folio/edge/patron/model/loanTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
New field in the charges object: feeFineId (UUID) (see example below):
```
{
"item" : {
"title" : "The Inverted World",
"author" : "Priest, Christopher",
"instanceId" : "4d9b1d4d-af36-4672-b876-b0bbf13c3622",
"itemId" : "09e7f3d2-ad88-4ce5-bfad-a42fc63ee41b",
"isbn" : "0008675309"
},
"chargeAmount" : {
"amount" : 1.23,
"isoCurrencyCode" : "USD"
},
"accrualDate" : "2018-05-08T19:25:20.941+0000",
"description" : "late fee",
"state" : "outstanding",
"reason" : "item overdue",
"feeFineId" : "45a8a1f3-a8b5-4485-afd9-05eed31017c4"
}
```
=> Add feeFineID to charges

pom.xml, src/test/java/org/folio/edge/patron/MainVerticleTest.java
The original implementation would log an error and continue w/ an empty string for the password when one could not be obtained from the secure store. This essentially pushed the responsibility of failing the request out to FOLIO.
Given that this will almost never work (empty passwords shouldn't be allowed anyway), we should just fail the request right then and there, before even making a request to FOLIO.
=> fast fail on missing password

pom.xml, src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/MainVerticle.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/cache/PatronIdCache.java, src/main/java/org/folio/edge/patron/utils/PatronIdHelper.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/cache/PatronIdCacheTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
It's unrealistic to think that existing users in an SSO IdP will have the same patron/user ID that's used within FOLIO.  As such, it's necessary to perform some mapping of external ID to internal ID.  The solution implemented uses the 'externalSystemId' field for this purpose.
- mod-users is queried using the provided (external patron ID)
- the external -> internal ID mapping is cached for a configurable amount of time
- once an internal ID is obtained, it's used for all subsequent calls into mod-patron
=> Patron mapping

src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/model/ErrorMessage.java, src/main/java/org/folio/edge/patron/model/error/Error.java, src/main/java/org/folio/edge/patron/model/error/ErrorMessage.java, src/main/java/org/folio/edge/patron/model/error/Errors.java, src/main/java/org/folio/edge/patron/model/error/Parameter.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/model/error/ErrorMessageTest.java, src/test/java/org/folio/edge/patron/model/error/ErrorTest.java, src/test/java/org/folio/edge/patron/model/error/ErrorsTest.java, src/test/java/org/folio/edge/patron/model/error/ParameterTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
Added a wrapper around the 400-500 error messages.
For errors with status code of 422, extracted the first error's message and created a wrapper around it. 
Added appropriate unit tests.
The Errors structures (Errors.java, Error.java, Parameter.java) are copied and pasted from generated code to reduce complexity.  I could potentially pull in the generated code instead of creating them anew here.
=> Error msg wrapper

pom.xml, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientCompressionTest.java
The latest release of edge-common has HTTP client compression support which will allow mod-patron to return compressed data without edge-patron sending compressed garbage to the client.
For good measure, I added a compression test that fails when using edge-common <= v2.0.1 but passes when using edge-common v2.0.2.
=> EDGPATRON-17: Use the latest release of edge-common

descriptors/ModuleDescriptor-template.json, pom.xml
We need to update the version of the `login` interface to include `6.0` in order to be compatible with the current release.
Also fixed some pom file Eclipse warnings.
=> EDGPATRON-18: update the login interface dependency to include 6.0

.gitignore, ramls/hold.json, ramls/patron.xsd, src/main/java/org/folio/edge/patron/PatronHandler.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
**Approach**
- Make requestDate optional
- For both instance- and item-level requests, replace the incoming requestDate with the timestamp, and if there isn't a requestDate in the JSON request, add the new requestDate element to send to mod-patron.
- Because the timestamp is in UTC and it can't be injected into the code at runtime, the unit tests need to compare the timestamps interval (within one minute).
- There isn't a need to do anything for request expiration date.  The expiration date is already not required, will only be populated if the client passes in, and only returned to the client if there's a value for it (set by the client).
=> EDGPATRON-19: Set request creation and expiration dates

src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java
Remove expirationDate from request (not passing it on to mod-patron) when it's proved to be invalid by attempting to parse the dateTime string into a **Date** object.
In the test, there is no simple way to create a Hold object that has an invalid Date object to call the RestAssured service, so I had to create a Hold object with a valid Date object first, then convert it to a string and use regular expression to swap out the date value to something invalid.
=> Edgpatron-19: Expiration Date

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> EDGPATRON-25 FOLIO-2358 manage container memory

pom.xml, src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/model/HoldCancellationValidator.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/model/HoldCancellationValidatorTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
Removed validation of the property canceledByUserId.
Updated tests to remove references to canceledByUserId.
It turns out that the validation code was the only place that makes use of canceledByUserId. It seems like the patronId that is eventually passed on to mod-patron for canceledByUserId is being extracted from the normal way by edge-common.
=> EDGEPATRON-27: Remove validation for canceledByUserId 

descriptors/ModuleDescriptor-template.json
Whilst trying to release `edge-patron` it became apparent that the dependencies might be incorrect.
This module makes requests to `/circulation/requests/{id}` endpoints meaning it needs to depend upon the `circulation` interface. I chose the same version that `mod-patron` [depends](https://github.com/folio-org/mod-patron/blob/e343d663d8d805d3b1250147137888fdaee955f4/descriptors/ModuleDescriptor-template.json#L68) upon for simplicity.
This module also expects the `patronComments` property for requests and that was introduced into the `patron` interface in [version 4.2](https://github.com/folio-org/mod-patron/pull/48/files) and so I have updated these to match as well.
=> Update dependencies for patron comments EDGPATRON-33

NEWS.md, descriptors/ModuleDescriptor-template.json
Add support for `circulation` `v10.0`. The important difference from `v9.5` is
the removal of the `override-checkout-by-barcode` endpoint which is not
used here.
Refs [EDGPATRON-44](https://issues.folio.org/browse/EDGPATRON-44)
=> EDGPATRON-44 support circulation v10.0

descriptors/ModuleDescriptor-template.json
Resolves [EDGPATRON-46](https://issues.folio.org/browse/EDGPATRON-46).
There is a breaking change in `mod-circulaion` that will be merge soon. Modules that have a dependency on `circulation` interface need to be updated to support version `11.0`.
There are multiple PRs with `circulation` interface version update, they all should be merged on the same day. 
**DO NOT MERGE** this PR until then.
=> EDGPATRON-46 Update circulation interface version

ramls/edge-patron.raml, src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientCompressionTest.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
Purpose:
https://issues.folio.org/browse/EDGPATRON-62
Approach:
Added support of new query params in **/patron/account/{id} API**, such as limit. offset, sortBy.
=> EDGPATRON-62 Add new params to getAcc API

NEWS.md, pom.xml
Resolve CVE-2021-44228 as per [EDGPATRON-67](https://issues.folio.org/browse/EDGPATRON-67).
=> EDGPATRON-67: Update Log4j to 2.16.0 (Kiwi R3 2021).

NEWS.md, pom.xml
Resolve CVE-2021-44228 as per [EDGPATRON-67](https://issues.folio.org/browse/EDGPATRON-67).
=> EDGPATRON-67: Update Log4j to 2.16.0 (Lotus).

NEWS.md, pom.xml, src/main/java/org/folio/edge/patron/MainVerticle.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/cache/PatronIdCache.java, src/main/java/org/folio/edge/patron/utils/PatronIdHelper.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/cache/PatronIdCacheTest.java, src/test/java/org/folio/edge/patron/model/AccountTest.java, src/test/java/org/folio/edge/patron/model/ChargeTest.java, src/test/java/org/folio/edge/patron/model/HoldCancellationTest.java, src/test/java/org/folio/edge/patron/model/HoldTest.java, src/test/java/org/folio/edge/patron/model/ItemTest.java, src/test/java/org/folio/edge/patron/model/MoneyTest.java, src/test/java/org/folio/edge/patron/model/loanTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientCompressionTest.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
The referenced ticket is originally for CVE-2021-44228.
However, that CVE does not exactly affect the 1.2 versions of Log4J (per-say).
A separate CVE (CVE-2021-4104) appears to have been created to reference a way to exploit the JNDI expoit mentioned in CVE-2021-4428 via the JMSAppender.
This required several additional code changes and should be reviewed for breaking changes.
I have tested that, with the changes applied, the logs do work with 2.16.0.
I am not familiar with `jcl-over-slf4j` and as such I am concerned with potential for breakage there.
The dependencies now look like:
```
[INFO] -----------------------< org.folio:edge-patron >------------------------
[INFO] Building Edge API - Patron Empowerment 4.5.0
[INFO] --------------------------------[ jar …
```
=> EDGPATRON-69: Update to Log4J 2.16.0 (Juniper R2 2021).

NEWS.md, pom.xml
Resolve CVE-2021-45105 as per [EDGPATRON-74](https://issues.folio.org/browse/EDGPATRON-74).
=> EDGPATRON-74: Update Log4j to 2.17.0 (Lotus).

NEWS.md, pom.xml
Resolve CVE-2021-45105 as per [EDGPATRON-74](https://issues.folio.org/browse/EDGPATRON-74).
=> EDGPATRON-74: Update Log4j to 2.17.0 (Kiwi R3 2021).

NEWS.md, pom.xml
Resolve CVE-2021-45105 as per [EDGPATRON-76](https://issues.folio.org/browse/EDGPATRON-76).
=> EDGPATRON-76: Update Log4j to 2.17.0 (Juniper R2 2021).

descriptors/ModuleDescriptor-template.json
Adapt the module to changed interface of mod-circulation from v12.0 to v13.0
Adapt ModuleDescriptor-template to circulation interface v13.0;
https://issues.folio.org/browse/EDGPATRON-79
=> EDGPATRON-79 Support circulation interface v13

Jenkinsfile, README.md, ramls/account.json, ramls/edge-patron.raml, ramls/money.json
[EDGPATRON-83](https://issues.folio.org/browse/EDGPATRON-83)
[FOLIO-3231](https://issues.folio.org/browse/FOLIO-3231)
The doApiLint facility replaces runLintRamlCop
https://dev.folio.org/guides/api-lint/
The doApiDoc facility replaces publishAPI
https://dev.folio.org/guides/api-doc/
=> EDGPATRON-83 Use new api-lint and api-doc CI facilities

src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/utils/PatronIdHelper.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
Timeout tests like MainVerticleTest.testPlaceInstanceHoldRequestTimeout have spurious test failures because CompletableFuture and Future may block each other:
```
12:46:48 INFO  MockOkapi            Waiting for 6000 ms before continuing
12:46:51 ERROR PatronHandler        Exception calling OKAPI
io.vertx.core.VertxException: Connection was closed
12:46:51 ERROR ?                    io.vertx.core.VertxException: Connection was closed
12:46:51 DEBUG Wire                  << "HTTP/1.1 500 Internal Server Error[\r][\n]"
12:46:51 DEBUG Wire                  << "content-type: application/json[\r][\n]"
12:46:51 DEBUG Wire                  << "content-length: 62[\r][\n]"
12:46:51 DEBUG Wire                  << "[\r][\n]"
12:46:51 DEBUG aultClientConnection Receiving response: HTTP/1.1 500 …
```
=> EDGPATRON-92: Replace CompletableFuture with Future, fix spurious failures

pom.xml
Upgrade woodstox-core from 5.0.3 to 6.2.7 fixing XML External Entity (XXE) Injection: https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLWOODSTOX-2928754
Upgrade jackson-databind from 2.11.3 to 2.13.2.1 fixing Denial of Service (DoS): https://nvd.nist.gov/vuln/detail/CVE-2020-36518 , https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-2326698
Upgrade jackson-dataformat-cbor from 2.11.3 to 2.13.2 fixing Denial of Service (DoS): https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Upgrade vertx from 4.1.0 to 4.3.1. This indirectly upgrades Netty from 4.1.65.Final to 4.1.77.Final fixing Denial of Service (DoS), HTTP Request Smuggling, and Information Exposure: https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-37136 , https://nvd.nist.gov/view/vuln/detail?vulnId=CVE-2021-37137 , …
=> EDGPATRON-91: Upgrade dependencies fixing DoS and HTTP Request Smuggling

pom.xml, src/test/java/org/folio/edge/patron/MainVerticleTest.java
How to reproduce: Use Java 17, run mvn clean install.
Expected: succeeds
Actual: fails with this error
```
[ERROR] org.folio.edge.patron.MainVerticleTest  Time elapsed: 1.124 s  <<< ERROR!
java.lang.ExceptionInInitializerError
at org.folio.edge.patron.MainVerticleTest.setUpOnce(MainVerticleTest.java:94)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @62bd2070
at org.folio.edge.patron.MainVerticleTest.setUpOnce(MainVerticleTest.java:94)
```
Fix: Use latest mockito.
=> EDGPATRON-95: Upgrade mockito from 1.95 to 4.6.1 for Java 17

pom.xml
This fixes disabled SSL in Vert.x 4.3.0/4.3.1.
=> EDGPATRON-99: Bump to Vert.x 4.3.3 and edge-common 4.4.1

NEWS.md, src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java
Requests to place holds on items with no JSON body were triggering a 500 error.
This is because the code was assuming a body would be included, which resulted 
in nullpointererrors when the code tried to access the request body.
I resolved this by adding a null check that generates a 400 error.  Since the hold 
request for instances was coded in almost the exact same way, I also added a
null check there.  Then I wrote tests for what happens when no value is supplied
in the hold body.
=> EDGPATRON-102: Adding null checking to hold placement

src/main/java/org/folio/edge/patron/PatronHandler.java
Edge-patron only communicates with two external modules:
mod-user (to look up the users UUID)
Mod-patron (everything else)
I've attached error messages to both that identify what module call was connected with the failure.
=> EDGPATRON-101: Improve error logging for external requests

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/edge-patron.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 EDGPATRON-112 Use GitHub Workflows api-lint and api-schema-lint and api-doc

ramls/edge-patron.raml, ramls/examples/external_patron_collection.json, ramls/external_patron_collection.json, src/main/java/org/folio/edge/patron/Constants.java, src/main/java/org/folio/edge/patron/MainVerticle.java, src/main/java/org/folio/edge/patron/PatronHandler.java, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/MainVerticleTest.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
https://folio-org.atlassian.net/browse/EDGPATRON-134
=> [EDGEPATRON-134]-Added Get Endpoint for expired External Patron

pom.xml
bump up edge-common to v4.7.1: AwsParamStore to support FIPS-approved crypto modules
=> EDGPATRON-139: Bump up edge-common to v4.7.1

ramls/examples/external_patron.json, ramls/examples/external_patron_collection.json, ramls/external_patron.json, src/main/java/org/folio/edge/patron/model/Patron.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
https://folio-org.atlassian.net/browse/EDGPATRON-141
=> [EDGEPATRON-141]-Removed Address0

ramls/edge-patron.raml, ramls/examples/staging_user.json, ramls/examples/user.json, ramls/examples/user_error.json, ramls/schemas/user_error_400.schema, ramls/schemas/user_error_404.schema, ramls/staging_user.json, ramls/userdata.json
**Purpose:**
The purpose of the jira is to implement EDGPATRON-151
=> EDGPATRON-151 Adding new api contract for Post and get api of LC User registration

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java, src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java, src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
https://folio-org.atlassian.net/browse/EDGPATRON-147
Assumption: feature flag for Secure Request and Secure Tenant ID are configured via environment variables
Expected logic: if we did not find a patron in the Central Tenant AND if the Secure Request feature is enabled, then call mod-users in the Congressional Tenant using `mod-circulation-bff`'s new endpoint (not implemented yet)
=> EDGPATRON-147 Patron lookup in the secure tenant
