folio-org/edge-patron

- pom.xml
- src/main/java/org/folio/edge/patron/utils/PatronIdHelper.java
- src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java
https://issues.folio.org/browse/EDGPATRON-1
> use vertxCompletableFuture

- .editorconfig
- NEWS.md
- pom.xml
- ramls/account.json
- ramls/charge.json
- ramls/hold.json
- ramls/item.json
- ramls/loan.json
- ramls/money.json
- src/main/resources/ephemeral.properties
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/model/error/ErrorMessageTest.java
Completed EDGPATRON-4: descriptions in the JSON schemas.
Cleaned up some warnings in the build and eclipse. Fixed some issues with tests on Windows.
> Pre-release cleanup

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/edge-patron.raml
- ramls/examples/hold.json
- ramls/hold.json
- src/main/java/org/folio/edge/patron/model/Hold.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/model/AccountTest.java
- src/test/java/org/folio/edge/patron/model/HoldTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
- src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
Complete EDGPATRON-9, EDGPATRON-7 and EDGPATRON-11. This brings the edge module in line with the latest `circulation` breaking changes as well as the latest `edge-common` breaking changes.
> Update to 2.0.0

- NEWS.md
- pom.xml
> merging temporary edge patron release 3.0.3 release branch

- README.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/edge/patron/Constants.java
- src/main/java/org/folio/edge/patron/PatronHandler.java
- src/main/java/org/folio/edge/patron/model/HoldCancellationValidator.java
- src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java
- src/test/java/org/folio/edge/patron/model/HoldCancellationValidatorTest.java
- src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
Provided a work-around for edge-patron's date deserializing issue where it doesn't even take a compliant ISO formatted date string.
> Workaround for Date formatting issue

- NEWS.md
- pom.xml
> Tmp edge-patron release 4.0.0

- NEWS.md
- pom.xml
Adding release notes and updating the pom file for the next development version.
> Tmp release 4.1.0

- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/edge/patron/model/Account.java
- src/main/java/org/folio/edge/patron/model/Charge.java
- src/main/java/org/folio/edge/patron/model/Hold.java
- src/main/java/org/folio/edge/patron/model/Item.java
- src/main/java/org/folio/edge/patron/model/Loan.java
- src/main/java/org/folio/edge/patron/model/Money.java
- src/main/java/org/folio/edge/patron/model/error/Error.java
- src/main/java/org/folio/edge/patron/model/error/ErrorMessage.java
- src/main/java/org/folio/edge/patron/model/error/Errors.java
- src/main/java/org/folio/edge/patron/model/error/Parameter.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
Jira: https://issues.folio.org/browse/EDGPATRON-35
> EDGPATRON-35: Upgrade to JDK 11

- .gitmodules
- ramls/edge-patron.raml
Update raml with possible 422 http code response
> EDGPATRON-22: Update raml with possible 422 http code response

- descriptors/ModuleDescriptor-template.json
- ramls/edge-patron.raml
- ramls/examples/hold.json
- ramls/hold.json
- ramls/patron.xsd
- src/main/java/org/folio/edge/patron/Constants.java
- src/main/java/org/folio/edge/patron/model/Hold.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/model/HoldTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
https://issues.folio.org/browse/EDGPATRON-33
EDGPATRON-33: Add patron notes to requests (EDGEPATRON)
* Added support of patronComments functionality.
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?  
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
> EDGPATRON-33: Add patron notes to requests (EDGEPATRON)

- pom.xml
As mainline versions should be major and minor versions only
> Change next version to 4.4.0 EDGPATRON-40

- ramls/edge-patron.raml
I neglected to upgrade the interface version in the initial push for this issue.
> EDGPATRON-61: Updating interface version to 4.2

- NEWS.md
- ramls/edge-patron.raml
See [EDGPATRON-63](https://issues.folio.org/browse/EDGPATRON-63).
> [EDGPATRON-63] Include API key parameter for every endpoint in RAML.

- NEWS.md
- pom.xml
[EDGPATRON-75](https://issues.folio.org/browse/EDGPATRON-75)
> EDGPATRON-75: Release 4.6.2.

- NEWS.md
- pom.xml
[EDGPATRON-77](https://issues.folio.org/browse/EDGPATRON-77)
> EDGPATRON-77: Release 4.5.2.

- descriptors/ModuleDescriptor-template.json
Resolves:https://issues.folio.org/browse/EDGPATRON-64
> EDGPATRON-64 Update circulation interface version

- ramls/edge-patron.raml
- src/main/java/org/folio/edge/patron/PatronHandler.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
- src/test/java/org/folio/edge/patron/utils/PatronOkapiClientTest.java
https://issues.folio.org/browse/EDGPATRON-72
- added limit min value in raml
- added logic for negative limit handling to PatronHandler
- added test
Current response :
> EDGPATRON-72 - Inconsistent handling of invalid limit parameter values

- NEWS.md
- pom.xml
> Tmp release 4.7.0

- pom.xml
- src/main/java/org/folio/edge/patron/MainVerticle.java
Also upgrades to make it closer to being able to run tests with Java 17. Unfortunately, not quite there yet as that requires fixes to edge-common it seems.
> Upgrade to edge-common 4.4.2 EDGPATRON-106

- descriptors/ModuleDescriptor-template.json
- src/test/resources/good-request.json
- src/test/resources/malformed-request.json
Changing patron and circulation interface versions to be in line with:
CIRC-253
MODPATRON-137
> EDGPATRON-113:updating interfaces

- descriptors/ModuleDescriptor-template.json
Resolves EDGPATRON-113, should fix failing Snapshot builds
> EDGPATRON-113 Fix patron interface version

- descriptors/ModuleDescriptor-template.json
- ramls/allowed-service-point.json
- ramls/allowed-service-points-response.json
- ramls/edge-patron.raml
- ramls/examples/allowed-service-points-response.json
- src/main/java/org/folio/edge/patron/MainVerticle.java
- src/main/java/org/folio/edge/patron/PatronHandler.java
- src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
- src/test/resources/allowed_sp_error_edge_patron.json
- src/test/resources/allowed_sp_error_mod_patron.json
- src/test/resources/allowed_sp_mod_patron_expected_response.json
[EDGPATRON-119](https://issues.folio.org/browse/EDGPATRON-119)
Discovery application need to know which service points are available as pickup locations.
> EDGPATRON-119 Add allowed-service-points endpoint

- NEWS.md
- pom.xml
Resolves: [EDGPATRON-121](https://issues.folio.org/browse/EDGPATRON-121)
> [EDGPATRON-121] Release v5.0.0

- NEWS.md
- pom.xml
Resolves: [EDGPATRON-128](https://folio-org.atlassian.net/browse/EDGPATRON-128)
> [EDGEPATRON-128] Upgrade Vertx to 4.5.5

- NEWS.md
- pom.xml
Resolves: [EDGPATRON-127](https://folio-org.atlassian.net/browse/EDGPATRON-127)
> [EDGEPATRON-127] Release 5.1.0

- descriptors/ModuleDescriptor-template.json
Resolves: [EDGPATRON-138](https://folio-org.atlassian.net/browse/EDGPATRON-138)
> EDGPATRON-138 Update patron interface version

- ramls/edge-patron.raml
- src/main/java/org/folio/edge/patron/Constants.java
- src/main/java/org/folio/edge/patron/MainVerticle.java
- src/main/java/org/folio/edge/patron/PatronHandler.java
- src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
https://folio-org.atlassian.net/browse/EDGPATRON-133
> [EDGEPATRON-133]-Added PUT endpoint.

- NEWS.md
- pom.xml
> Bugfix release 5.1.2

- src/main/resources/ephemeral.properties
https://folio-org.atlassian.net/browse/FAT-15263
> FAT-15263: added edge-patron karate test tenant in ephemeral

- ramls/examples/external_patron_collection.json
- ramls/external_patron.json
https://folio-org.atlassian.net/browse/EDGPATRON-143
> EDGPATRON-143: fixed PreferredEmailCommunication Service to Services

- NEWS.md
- pom.xml
Purpose:
[EDGPATRON-152](https://folio-org.atlassian.net/browse/EDGPATRON-152)
> EDGPATRON-152: Release 5.2.0

- ramls/edge-patron.raml
- src/main/java/org/folio/edge/patron/PatronHandler.java
- src/main/java/org/folio/edge/patron/utils/PatronOkapiClient.java
- src/test/java/org/folio/edge/patron/MainVerticleTest.java
- src/test/java/org/folio/edge/patron/utils/PatronMockOkapi.java
- src/test/resources/user_active.json
Extend get API for /patron/registration-status with {externalSystemId}
> [EDGPATRON-161] - Extend get API for /patron/registration-status with externalSystemId

- pom.xml
- src/main/java/org/folio/edge/patron/PatronHandler.java
https://folio-org.atlassian.net/browse/EDGPATRON-156
Upgrade AWS SDK and edge-common dependencies.
> EDGPATRON-156: Migrate AWS SDK for Java from 1.x to 2.x

- NEWS.md
- pom.xml
Resolves: [https://folio-org.atlassian.net/browse/EDGPATRON-181](https://folio-org.atlassian.net/browse/EDGPATRON-181)
> EDGPATRON-181 Release 5.3.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/allowed-service-point.json
- ramls/examples/allowed-service-points-response.json
- src/test/resources/allowed_sp_mod_patron_expected_response.json
https://folio-org.atlassian.net/browse/EDGPATRON-186
> Ramsons (CSP#3) release 5.2.2
